[tox]

[testenv]
extras =
    testsite

commands =
    mypy --install-types --non-interactive src/climateclaw_client
    isort --check src/climateclaw_client -l 100
    black --line-length 100 --check src/climateclaw_client
    blackdoc --check src/climateclaw_client
    flake8 src/climateclaw_client
    pytest -v --cov --cov-branch --cov-fail-under=95

[pytest]
python_files = tests.py test_*.py *_tests.py
norecursedirs = .* build dist *.egg venv docs
