[tox]

[testenv]
extras =
    testsite

commands =
    mypy --install-types --non-interactive src/freva_gpt_client
    isort --check src/freva_gpt_client -l 100
    black --line-length 100 --check src/freva_gpt_client
    blackdoc --check src/freva_gpt_client
    flake8 src/freva_gpt_client
    pytest -v --cov=src/freva_gpt_client -x 

[pytest]
python_files = tests.py test_*.py *_tests.py
norecursedirs = .* build dist *.egg venv docs